apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
spec:
  selector:                                                                                                    
    app: springboot
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer